# Generated by Django 3.1.4 on 2020-12-12 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets_api_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='market',
            old_name='address',
            new_name='market_name',
        ),
    ]
